import os

TWELVE_DATA_API_KEY = os.getenv("TWELVE_DATA_API_KEY")
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

MARKETS = {"XAU/USD": "GOLD"}
TIMEFRAME = "5min"
CANDLE_LIMIT = 200

EMA_FAST = 20
EMA_SLOW = 50
RSI_PERIOD = 14
ADX_PERIOD = 14
ATR_PERIOD = 14

MIN_CONFIDENCE = 60
MIN_ADX = 20

CANDLE_MINUTES = 5
CHECK_DELAY_SECONDS = 5
